# Generated by Django 3.1.2 on 2020-10-30 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kospi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('close', models.DecimalField(decimal_places=3, max_digits=8)),
                ('open', models.DecimalField(decimal_places=3, max_digits=8)),
                ('high', models.DecimalField(decimal_places=3, max_digits=8)),
                ('low', models.DecimalField(decimal_places=3, max_digits=8)),
                ('volume', models.FloatField()),
                ('d1_diff_rate', models.DecimalField(decimal_places=3, max_digits=6)),
            ],
            options={
                'db_table': 'kospi',
                'ordering': ['-pk'],
            },
        ),
    ]
