# Generated by Django 3.1.2 on 2020-11-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc_api', '0003_snippet_snippetamount_snippetbuy_snippetscope_snippetsell'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='type',
            field=models.CharField(default='scope', max_length=10),
            preserve_default=False,
        ),
    ]
