# Generated by Django 3.1.2 on 2020-11-09 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qc_api', '0005_algorithm'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='algorithm',
            table='algorithm',
        ),
    ]
